//
//  BoardCG.swift
//  (null)
//
//  Created by Igor Ivanov on 14.09.2020.
//  Copyright © 2020 (null). All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class BoardCG : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawBoardView(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 372, height: 372), resizing: ResizingBehavior = .aspectFit, pos0: String = "X", pos1: String = "X", pos2: String = "X", pos3: String = "X", pos4: String = "X", pos5: String = "X", pos6: String = "0", pos7: String = "X", pos8: String = "X", winLineNo: CGFloat = -1, winMsg: String = "") {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 372, height: 372), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 372, y: resizedFrame.height / 372)


        //// Color Declarations
        let gradientColor = UIColor(red: 0.130, green: 0.000, blue: 1.000, alpha: 1.000)
        let color = UIColor(red: 0.000, green: 0.940, blue: 1.000, alpha: 1.000)
        let color2 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.263)
        let color3 = UIColor(red: 0.000, green: 1.000, blue: 0.937, alpha: 1.000)

        //// Gradient Declarations
        let gradient = CGGradient(colorsSpace: nil, colors: [UIColor.black.cgColor, gradientColor.cgColor] as CFArray, locations: [0, 1])!

        //// Variable Declarations
        let lineExp0: CGFloat = winLineNo == 0 ? 1 : 0
        let lineExp1: CGFloat = winLineNo == 1 ? 1 : 0
        let lineExp2: CGFloat = winLineNo == 2 ? 1 : 0
        let lineExp3: CGFloat = winLineNo == 3 ? 1 : 0
        let lineExp4: CGFloat = winLineNo == 4 ? 1 : 0
        let lineExp5: CGFloat = winLineNo == 5 ? 1 : 0
        let lineExp6: CGFloat = winLineNo == 6 ? 1 : 0
        let lineExp7: CGFloat = winLineNo == 7 ? 1 : 0
        let drawMsgExp: CGFloat = winLineNo == 8 ? 1 : 0
        let winMsgExp: CGFloat = winMsg != "" ? 1 : 0

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 372, height: 372))
        context.saveGState()
        rectanglePath.addClip()
        context.drawLinearGradient(gradient, start: CGPoint(x: 186, y: 0), end: CGPoint(x: 186, y: 372), options: [])
        context.restoreGState()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 124, height: 124))
        color2.setFill()
        rectangle2Path.fill()
        color.setStroke()
        rectangle2Path.lineWidth = 1
        rectangle2Path.stroke()


        //// Rectangle 3 Drawing
        let rectangle3Path = UIBezierPath(rect: CGRect(x: 248, y: 0, width: 124, height: 124))
        color2.setFill()
        rectangle3Path.fill()
        color.setStroke()
        rectangle3Path.lineWidth = 1
        rectangle3Path.stroke()


        //// Rectangle 4 Drawing
        let rectangle4Path = UIBezierPath(rect: CGRect(x: 124, y: 0, width: 124, height: 124))
        color2.setFill()
        rectangle4Path.fill()
        color.setStroke()
        rectangle4Path.lineWidth = 1
        rectangle4Path.stroke()


        //// Rectangle 5 Drawing
        let rectangle5Path = UIBezierPath(rect: CGRect(x: 0, y: 124, width: 124, height: 124))
        color2.setFill()
        rectangle5Path.fill()
        color.setStroke()
        rectangle5Path.lineWidth = 1
        rectangle5Path.stroke()


        //// Rectangle 6 Drawing
        let rectangle6Path = UIBezierPath(rect: CGRect(x: 124, y: 124, width: 124, height: 124))
        color2.setFill()
        rectangle6Path.fill()
        color.setStroke()
        rectangle6Path.lineWidth = 1
        rectangle6Path.stroke()


        //// Rectangle 7 Drawing
        let rectangle7Path = UIBezierPath(rect: CGRect(x: 248, y: 124, width: 124, height: 124))
        color2.setFill()
        rectangle7Path.fill()
        color.setStroke()
        rectangle7Path.lineWidth = 1
        rectangle7Path.stroke()


        //// Rectangle 8 Drawing
        let rectangle8Path = UIBezierPath(rect: CGRect(x: 0.5, y: 247.5, width: 124, height: 124))
        color2.setFill()
        rectangle8Path.fill()
        color.setStroke()
        rectangle8Path.lineWidth = 1
        rectangle8Path.stroke()


        //// Rectangle 9 Drawing
        let rectangle9Path = UIBezierPath(rect: CGRect(x: 124, y: 248, width: 124, height: 124))
        color2.setFill()
        rectangle9Path.fill()
        color.setStroke()
        rectangle9Path.lineWidth = 1
        rectangle9Path.stroke()


        //// Rectangle 10 Drawing
        let rectangle10Path = UIBezierPath(rect: CGRect(x: 248, y: 248, width: 124, height: 124))
        color2.setFill()
        rectangle10Path.fill()
        color.setStroke()
        rectangle10Path.lineWidth = 1
        rectangle10Path.stroke()


        //// Text Drawing
        let textRect = CGRect(x: 31, y: 34, width: 59, height: 58)
        let textStyle = NSMutableParagraphStyle()
        textStyle.alignment = .center
        let textFontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: textStyle,
        ] as [NSAttributedString.Key: Any]

        let textTextHeight: CGFloat = pos0.boundingRect(with: CGSize(width: textRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: textFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: textRect)
        pos0.draw(in: CGRect(x: textRect.minX, y: textRect.minY + (textRect.height - textTextHeight) / 2, width: textRect.width, height: textTextHeight), withAttributes: textFontAttributes)
        context.restoreGState()


        //// Text 2 Drawing
        let text2Rect = CGRect(x: 157, y: 33, width: 59, height: 58)
        let text2Style = NSMutableParagraphStyle()
        text2Style.alignment = .center
        let text2FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text2Style,
        ] as [NSAttributedString.Key: Any]

        let text2TextHeight: CGFloat = pos1.boundingRect(with: CGSize(width: text2Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text2FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text2Rect)
        pos1.draw(in: CGRect(x: text2Rect.minX, y: text2Rect.minY + (text2Rect.height - text2TextHeight) / 2, width: text2Rect.width, height: text2TextHeight), withAttributes: text2FontAttributes)
        context.restoreGState()


        //// Text 3 Drawing
        let text3Rect = CGRect(x: 281, y: 34, width: 59, height: 58)
        let text3Style = NSMutableParagraphStyle()
        text3Style.alignment = .center
        let text3FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text3Style,
        ] as [NSAttributedString.Key: Any]

        let text3TextHeight: CGFloat = pos2.boundingRect(with: CGSize(width: text3Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text3FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text3Rect)
        pos2.draw(in: CGRect(x: text3Rect.minX, y: text3Rect.minY + (text3Rect.height - text3TextHeight) / 2, width: text3Rect.width, height: text3TextHeight), withAttributes: text3FontAttributes)
        context.restoreGState()


        //// Text 4 Drawing
        let text4Rect = CGRect(x: 31, y: 157, width: 59, height: 58)
        let text4Style = NSMutableParagraphStyle()
        text4Style.alignment = .center
        let text4FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text4Style,
        ] as [NSAttributedString.Key: Any]

        let text4TextHeight: CGFloat = pos3.boundingRect(with: CGSize(width: text4Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text4FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text4Rect)
        pos3.draw(in: CGRect(x: text4Rect.minX, y: text4Rect.minY + (text4Rect.height - text4TextHeight) / 2, width: text4Rect.width, height: text4TextHeight), withAttributes: text4FontAttributes)
        context.restoreGState()


        //// Text 5 Drawing
        let text5Rect = CGRect(x: 157, y: 157, width: 59, height: 58)
        let text5Style = NSMutableParagraphStyle()
        text5Style.alignment = .center
        let text5FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text5Style,
        ] as [NSAttributedString.Key: Any]

        let text5TextHeight: CGFloat = pos4.boundingRect(with: CGSize(width: text5Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text5FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text5Rect)
        pos4.draw(in: CGRect(x: text5Rect.minX, y: text5Rect.minY + (text5Rect.height - text5TextHeight) / 2, width: text5Rect.width, height: text5TextHeight), withAttributes: text5FontAttributes)
        context.restoreGState()


        //// Text 6 Drawing
        let text6Rect = CGRect(x: 281, y: 157, width: 59, height: 58)
        let text6Style = NSMutableParagraphStyle()
        text6Style.alignment = .center
        let text6FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text6Style,
        ] as [NSAttributedString.Key: Any]

        let text6TextHeight: CGFloat = pos5.boundingRect(with: CGSize(width: text6Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text6FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text6Rect)
        pos5.draw(in: CGRect(x: text6Rect.minX, y: text6Rect.minY + (text6Rect.height - text6TextHeight) / 2, width: text6Rect.width, height: text6TextHeight), withAttributes: text6FontAttributes)
        context.restoreGState()


        //// Text 7 Drawing
        let text7Rect = CGRect(x: 33, y: 280, width: 59, height: 58)
        let text7Style = NSMutableParagraphStyle()
        text7Style.alignment = .center
        let text7FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text7Style,
        ] as [NSAttributedString.Key: Any]

        let text7TextHeight: CGFloat = pos6.boundingRect(with: CGSize(width: text7Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text7FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text7Rect)
        pos6.draw(in: CGRect(x: text7Rect.minX, y: text7Rect.minY + (text7Rect.height - text7TextHeight) / 2, width: text7Rect.width, height: text7TextHeight), withAttributes: text7FontAttributes)
        context.restoreGState()


        //// Text 8 Drawing
        let text8Rect = CGRect(x: 157, y: 281, width: 59, height: 58)
        let text8Style = NSMutableParagraphStyle()
        text8Style.alignment = .center
        let text8FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text8Style,
        ] as [NSAttributedString.Key: Any]

        let text8TextHeight: CGFloat = pos7.boundingRect(with: CGSize(width: text8Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text8FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text8Rect)
        pos7.draw(in: CGRect(x: text8Rect.minX, y: text8Rect.minY + (text8Rect.height - text8TextHeight) / 2, width: text8Rect.width, height: text8TextHeight), withAttributes: text8FontAttributes)
        context.restoreGState()


        //// Text 9 Drawing
        let text9Rect = CGRect(x: 281, y: 281, width: 59, height: 58)
        let text9Style = NSMutableParagraphStyle()
        text9Style.alignment = .center
        let text9FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48, weight: .bold),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text9Style,
        ] as [NSAttributedString.Key: Any]

        let text9TextHeight: CGFloat = pos8.boundingRect(with: CGSize(width: text9Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text9FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text9Rect)
        pos8.draw(in: CGRect(x: text9Rect.minX, y: text9Rect.minY + (text9Rect.height - text9TextHeight) / 2, width: text9Rect.width, height: text9TextHeight), withAttributes: text9FontAttributes)
        context.restoreGState()


        //// line7 Drawing
        context.saveGState()
        context.translateBy(x: 43, y: 325.46)
        context.rotate(by: -45 * CGFloat.pi/180)

        context.saveGState()
        context.setAlpha(lineExp7)

        let line7Path = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 400, height: 5), cornerRadius: 2.5)
        color3.setFill()
        line7Path.fill()

        context.restoreGState()

        context.restoreGState()


        //// line6 Drawing
        context.saveGState()
        context.translateBy(x: 46.54, y: 43.62)
        context.rotate(by: 45 * CGFloat.pi/180)

        context.saveGState()
        context.setAlpha(lineExp6)

        let line6Path = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 400, height: 5), cornerRadius: 2.5)
        color3.setFill()
        line6Path.fill()

        context.restoreGState()

        context.restoreGState()


        //// line5 Drawing
        context.saveGState()
        context.setAlpha(lineExp5)

        let line5Path = UIBezierPath(rect: CGRect(x: 0, y: 307, width: 371, height: 5))
        color3.setFill()
        line5Path.fill()

        context.restoreGState()


        //// line4 Drawing
        context.saveGState()
        context.setAlpha(lineExp4)

        let line4Path = UIBezierPath(rect: CGRect(x: 1, y: 183, width: 371, height: 5))
        color3.setFill()
        line4Path.fill()

        context.restoreGState()


        //// line3 Drawing
        context.saveGState()
        context.setAlpha(lineExp3)

        let line3Path = UIBezierPath(rect: CGRect(x: 0, y: 60, width: 371, height: 5))
        color3.setFill()
        line3Path.fill()

        context.restoreGState()


        //// line2 Drawing
        context.saveGState()
        context.translateBy(x: 308, y: 371)
        context.rotate(by: -90 * CGFloat.pi/180)

        context.saveGState()
        context.setAlpha(lineExp2)

        let line2Path = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 371, height: 5))
        color3.setFill()
        line2Path.fill()

        context.restoreGState()

        context.restoreGState()


        //// line1 Drawing
        context.saveGState()
        context.translateBy(x: 184, y: 372)
        context.rotate(by: -90 * CGFloat.pi/180)

        context.saveGState()
        context.setAlpha(lineExp1)

        let line1Path = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 371, height: 5))
        color3.setFill()
        line1Path.fill()

        context.restoreGState()

        context.restoreGState()


        //// line0 Drawing
        context.saveGState()
        context.translateBy(x: 58, y: 371)
        context.rotate(by: -90 * CGFloat.pi/180)

        context.saveGState()
        context.setAlpha(lineExp0)

        let line0Path = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 371, height: 5))
        color3.setFill()
        line0Path.fill()

        context.restoreGState()

        context.restoreGState()


        //// Text 10 Drawing
        context.saveGState()
        context.setAlpha(drawMsgExp)
        context.beginTransparencyLayer(auxiliaryInfo: nil)

        let text10Rect = CGRect(x: 33, y: 144, width: 307, height: 87)
        let text10Path = UIBezierPath(rect: text10Rect)
        UIColor.blue.setFill()
        text10Path.fill()
        let text10TextContent = "НИЧЬЯ!"
        let text10Style = NSMutableParagraphStyle()
        text10Style.alignment = .center
        let text10FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text10Style,
        ] as [NSAttributedString.Key: Any]

        let text10TextHeight: CGFloat = text10TextContent.boundingRect(with: CGSize(width: text10Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text10FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text10Rect)
        text10TextContent.draw(in: CGRect(x: text10Rect.minX, y: text10Rect.minY + (text10Rect.height - text10TextHeight) / 2, width: text10Rect.width, height: text10TextHeight), withAttributes: text10FontAttributes)
        context.restoreGState()

        context.endTransparencyLayer()
        context.restoreGState()


        //// Text 11 Drawing
        context.saveGState()
        context.setAlpha(winMsgExp)
        context.beginTransparencyLayer(auxiliaryInfo: nil)

        let text11Rect = CGRect(x: 33, y: 126, width: 307, height: 121)
        let text11Path = UIBezierPath(rect: text11Rect)
        UIColor.blue.setFill()
        text11Path.fill()
        let text11Style = NSMutableParagraphStyle()
        text11Style.alignment = .center
        let text11FontAttributes = [
            .font: UIFont.systemFont(ofSize: 48),
            .foregroundColor: UIColor.white,
            .paragraphStyle: text11Style,
        ] as [NSAttributedString.Key: Any]

        let text11TextHeight: CGFloat = winMsg.boundingRect(with: CGSize(width: text11Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: text11FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: text11Rect)
        winMsg.draw(in: CGRect(x: text11Rect.minX, y: text11Rect.minY + (text11Rect.height - text11TextHeight) / 2, width: text11Rect.width, height: text11TextHeight), withAttributes: text11FontAttributes)
        context.restoreGState()

        context.endTransparencyLayer()
        context.restoreGState()
        
        context.restoreGState()

    }




    @objc(BoardCGResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
